// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteConfig(arg1:string):Promise<void>;

export function GetConfig(arg1:string):Promise<string>;

export function GetOrSet(arg1:string,arg2:string):Promise<string>;

export function SetConfig(arg1:string,arg2:string):Promise<void>;
