// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteConfig(arg1) {
  return window['go']['api']['ConfigAPI']['DeleteConfig'](arg1);
}

export function GetConfig(arg1) {
  return window['go']['api']['ConfigAPI']['GetConfig'](arg1);
}

export function GetOrSet(arg1, arg2) {
  return window['go']['api']['ConfigAPI']['GetOrSet'](arg1, arg2);
}

export function SetConfig(arg1, arg2) {
  return window['go']['api']['ConfigAPI']['SetConfig'](arg1, arg2);
}
