// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {api} from '../models';

export function AbortScan(arg1:string):Promise<void>;

export function ClearScanHistory():Promise<void>;

export function FileContent(arg1:string,arg2:string):Promise<string>;

export function LoadScanHistory(arg1:number):Promise<Array<api.ScanHistoryRecord>>;

export function PauseScan(arg1:string):Promise<void>;

export function PollStatus(arg1:string):Promise<api.ScanStatusResponse>;

export function RecoveryProgress(arg1:string):Promise<api.RecoveryStatus>;

export function ResumeScan(arg1:string):Promise<void>;

export function ScanResult(arg1:string):Promise<api.ScanResultResponse>;

export function SetCurrentScan(arg1:string):Promise<void>;

export function StartRecovery(arg1:string,arg2:Array<string>,arg3:string):Promise<void>;

export function StartScan(arg1:string,arg2:string):Promise<string>;
