// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AbortScan(arg1) {
  return window['go']['api']['ScanAPI']['AbortScan'](arg1);
}

export function ClearScanHistory() {
  return window['go']['api']['ScanAPI']['ClearScanHistory']();
}

export function FileContent(arg1, arg2) {
  return window['go']['api']['ScanAPI']['FileContent'](arg1, arg2);
}

export function LoadScanHistory(arg1) {
  return window['go']['api']['ScanAPI']['LoadScanHistory'](arg1);
}

export function PauseScan(arg1) {
  return window['go']['api']['ScanAPI']['PauseScan'](arg1);
}

export function PollStatus(arg1) {
  return window['go']['api']['ScanAPI']['PollStatus'](arg1);
}

export function RecoveryProgress(arg1) {
  return window['go']['api']['ScanAPI']['RecoveryProgress'](arg1);
}

export function ResumeScan(arg1) {
  return window['go']['api']['ScanAPI']['ResumeScan'](arg1);
}

export function ScanResult(arg1) {
  return window['go']['api']['ScanAPI']['ScanResult'](arg1);
}

export function SetCurrentScan(arg1) {
  return window['go']['api']['ScanAPI']['SetCurrentScan'](arg1);
}

export function StartRecovery(arg1, arg2, arg3) {
  return window['go']['api']['ScanAPI']['StartRecovery'](arg1, arg2, arg3);
}

export function StartScan(arg1, arg2) {
  return window['go']['api']['ScanAPI']['StartScan'](arg1, arg2);
}
