// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DataDir() {
  return window['go']['api']['SystemAPI']['DataDir']();
}

export function DefaultOutputDir() {
  return window['go']['api']['SystemAPI']['DefaultOutputDir']();
}

export function ListDevices() {
  return window['go']['api']['SystemAPI']['ListDevices']();
}

export function WorkingDir() {
  return window['go']['api']['SystemAPI']['WorkingDir']();
}
