// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {api} from '../models';

export function ListDevices():Promise<Array<api.DeviceInfo>>;

export function WorkingDir():Promise<string>;
