// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function OpenFileDialog(arg1, arg2) {
  return window['go']['app']['App']['OpenFileDialog'](arg1, arg2);
}

export function OpenFolderDialog() {
  return window['go']['app']['App']['OpenFolderDialog']();
}
