// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';

export function OpenFileDialog(arg1:string,arg2:Array<app.FileDialogFilter>):Promise<string>;

export function OpenFolderDialog():Promise<string>;
